CREATE TABLE IF NOT EXISTS public.website_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  path TEXT NOT NULL CHECK (char_length(path) BETWEEN 1 AND 512 AND left(path, 1) = '/'),
  referrer TEXT NULL CHECK (referrer IS NULL OR char_length(referrer) <= 2048),
  utm_source TEXT NULL CHECK (utm_source IS NULL OR char_length(utm_source) <= 128),
  utm_medium TEXT NULL CHECK (utm_medium IS NULL OR char_length(utm_medium) <= 128),
  device_type TEXT NOT NULL DEFAULT 'unknown' CHECK (device_type IN ('desktop', 'mobile', 'tablet', 'bot', 'unknown')),
  user_id UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  session_id TEXT NOT NULL CHECK (session_id ~ '^[A-Za-z0-9_-]{8,128}$'),
  ip_hash TEXT NOT NULL CHECK (ip_hash ~ '^[A-Fa-f0-9]{64}$')
);

CREATE INDEX IF NOT EXISTS website_visits_visited_at_idx ON public.website_visits (visited_at DESC);
CREATE INDEX IF NOT EXISTS website_visits_path_idx ON public.website_visits (path);
CREATE INDEX IF NOT EXISTS website_visits_session_ip_idx ON public.website_visits (session_id, ip_hash, visited_at DESC);

ALTER TABLE public.website_visits ENABLE ROW LEVEL SECURITY;

GRANT INSERT ON TABLE public.website_visits TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.website_visits_id_seq TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.website_visits_within_rate_limit(
  _session_id TEXT,
  _ip_hash TEXT,
  _window INTERVAL DEFAULT interval '1 minute',
  _max_hits INTEGER DEFAULT 30
)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT (
    SELECT count(*)
    FROM public.website_visits
    WHERE session_id = _session_id
      AND ip_hash = _ip_hash
      AND visited_at >= now() - _window
  ) < _max_hits;
$$;

DROP POLICY IF EXISTS "Website visits insert anon/auth" ON public.website_visits;
CREATE POLICY "Website visits insert anon/auth"
ON public.website_visits
FOR INSERT
TO anon, authenticated
WITH CHECK (
  visited_at >= now() - interval '10 minutes'
  AND visited_at <= now() + interval '1 minute'
  AND (auth.uid() IS NULL OR user_id = auth.uid())
  AND public.website_visits_within_rate_limit(session_id, ip_hash, interval '1 minute', 30)
);

DROP POLICY IF EXISTS "Website visits select admins" ON public.website_visits;
CREATE POLICY "Website visits select admins"
ON public.website_visits
FOR SELECT
TO authenticated
USING (public.has_role(auth.uid(), 'admin'::app_role));

CREATE OR REPLACE FUNCTION public.get_website_visit_analytics()
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _is_admin BOOLEAN;
  _result JSONB;
BEGIN
  _is_admin := public.has_role(auth.uid(), 'admin'::app_role);
  IF NOT _is_admin THEN
    RAISE EXCEPTION 'Only admins can access website visit analytics';
  END IF;

  SELECT jsonb_build_object(
    'totals', jsonb_build_object(
      'today', (SELECT count(*) FROM public.website_visits WHERE visited_at >= date_trunc('day', now())),
      'days7', (SELECT count(*) FROM public.website_visits WHERE visited_at >= now() - interval '7 days'),
      'days30', (SELECT count(*) FROM public.website_visits WHERE visited_at >= now() - interval '30 days')
    ),
    'top_pages', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object('path', t.path, 'visits', t.visits)
        ORDER BY t.visits DESC, t.path
      )
      FROM (
        SELECT path, count(*)::BIGINT AS visits
        FROM public.website_visits
        WHERE visited_at >= now() - interval '30 days'
        GROUP BY path
        ORDER BY visits DESC, path
        LIMIT 10
      ) AS t
    ), '[]'::jsonb),
    'daily', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object('date', to_char(d.day, 'YYYY-MM-DD'), 'visits', COALESCE(v.visits, 0))
        ORDER BY d.day
      )
      FROM (
        SELECT generate_series(
          date_trunc('day', now()) - interval '29 days',
          date_trunc('day', now()),
          interval '1 day'
        )::date AS day
      ) d
      LEFT JOIN (
        SELECT date_trunc('day', visited_at)::date AS day, count(*)::BIGINT AS visits
        FROM public.website_visits
        WHERE visited_at >= date_trunc('day', now()) - interval '29 days'
        GROUP BY 1
      ) v ON v.day = d.day
    ), '[]'::jsonb)
  ) INTO _result;

  RETURN _result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_website_visit_analytics() TO authenticated;
